version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/my.cnf:/etc/my.cnf               # 配置文件
      - ./initdb:/docker-entrypoint-initdb.d    # 初始化数据库脚本
      - ./data:/var/lib/mysql                   # 数据库数据存储位置
    environment:
      - MYSQL_USER=${user}
      - MYSQL_PASSWORD=${passwd}
      - MYSQL_ROOT_PASSWORD=${root_passwd}
    networks:
        default:
            ipv4_address: 192.168.5.10

# docker network create --driver bridge --subnet 192.168.5.0/25 --gateway 192.168.5.1  unite_net

networks:
  default:
    external: true
    name: unite_net