version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime
      - ./initdb:/docker-entrypoint-initdb.d    # 初始化数据库脚本
      - ./data:/var/lib/mysql                   # 数据库数据存储位置
      - ./conf/my.cnf:/etc/my.cnf               # 配置文件
    environment:
      - MYSQL_ROOT_PASSWORD=${passwd}
